// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniGate.Infrastructure.Data;

#nullable disable

namespace UniGate.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123062457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniGate.Domain.Entities.Combo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.ComboSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ComboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.ToTable("ComboSubjects");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.MajorCombo", b =>
                {
                    b.Property<Guid>("MajorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComboId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MajorId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("MajorCombos");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.UserScores", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("DGNL_NgonNgu")
                        .HasColumnType("real");

                    b.Property<float?>("DGNL_Toan")
                        .HasColumnType("real");

                    b.Property<float?>("DGNL_TuDuy")
                        .HasColumnType("real");

                    b.Property<float?>("DiemCongThem")
                        .HasColumnType("real");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HB_CongNghe_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_CongNghe_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_CongNghe_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Dia_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Dia_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Dia_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_GDKTPL_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_GDKTPL_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_GDKTPL_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Hoa_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Hoa_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Hoa_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Ly_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Ly_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Ly_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_NgoaiNgu_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_NgoaiNgu_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_NgoaiNgu_12")
                        .HasColumnType("real");

                    b.Property<string>("HB_NgoaiNgu_Mon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HB_Sinh_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Sinh_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Sinh_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Su_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Su_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Su_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Tin_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Tin_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Tin_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Toan_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Toan_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Toan_12")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Van_10")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Van_11")
                        .HasColumnType("real");

                    b.Property<float?>("HB_Van_12")
                        .HasColumnType("real");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Thpt_Toan")
                        .HasColumnType("real");

                    b.Property<float?>("Thpt_TuChon1_Diem")
                        .HasColumnType("real");

                    b.Property<string>("Thpt_TuChon1_Mon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Thpt_TuChon2_Diem")
                        .HasColumnType("real");

                    b.Property<string>("Thpt_TuChon2_Mon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Thpt_Van")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.UserSelectedCombo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComboId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("UserSelectedCombos");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.ComboSubject", b =>
                {
                    b.HasOne("UniGate.Domain.Entities.Combo", "Combo")
                        .WithMany("Subjects")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.Major", b =>
                {
                    b.HasOne("UniGate.Domain.Entities.School", "School")
                        .WithMany("Majors")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.MajorCombo", b =>
                {
                    b.HasOne("UniGate.Domain.Entities.Combo", "Combo")
                        .WithMany("MajorCombos")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Domain.Entities.Major", "Major")
                        .WithMany("MajorCombos")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.UserScores", b =>
                {
                    b.HasOne("UniGate.Domain.Entities.User", "User")
                        .WithOne("Scores")
                        .HasForeignKey("UniGate.Domain.Entities.UserScores", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.UserSelectedCombo", b =>
                {
                    b.HasOne("UniGate.Domain.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.Combo", b =>
                {
                    b.Navigation("MajorCombos");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.Major", b =>
                {
                    b.Navigation("MajorCombos");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.School", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("UniGate.Domain.Entities.User", b =>
                {
                    b.Navigation("Scores")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
