<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>

	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniGate.Domain\UniGate.Domain.csproj" />
    <ProjectReference Include="..\UniGate.Shared\UniGate.Shared.csproj" />
  </ItemGroup>

</Project>
